steps:
  # 1. Build the container image passing NextJS compile-time build args
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/get200-app-api-repo/frontend:$SHORT_SHA'
      - '.'

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/get200-app-api-repo/frontend:$SHORT_SHA']

  # 3. Apply manifests (Deployment, HPA, Service, Ingress) to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/', '--namespace=get200']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

  # 4. Set the newly built image version in the deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/get200-frontend'
      - 'get200-frontend=asia-south1-docker.pkg.dev/$PROJECT_ID/get200-app-api-repo/frontend:$SHORT_SHA'
      - '--namespace=get200'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

substitutions:
  _ZONE: asia-south1
  _CLUSTER_NAME: nyc-r2-web
  _NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_Z3VpZGluZy1qZW5uZXQtNzkuY2xlcmsuYWNjb3VudHMuZGV2JA
  _NEXT_PUBLIC_API_URL: https://api.get200.qd.je

options:
  logging: CLOUD_LOGGING_ONLY
